# Generated by Django 4.1 on 2022-09-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_usuario_cedula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
    ]
